apiVersion: apps/v1
kind: Deployment
metadata:
name: react-frontend

spec:
replicas: 2

selector:
matchLabels:
app: react-frontend

template:
metadata:
labels:
app: react-frontend

```
spec:
  imagePullSecrets:
    - name: ecr-secret

  containers:
    - name: react-frontend
      image: 283372067875.dkr.ecr.us-east-1.amazonaws.com/react-frontend:latest
      imagePullPolicy: Always

      ports:
        - containerPort: 80


